spring.application.name=urlshortener

spring.datasource.master.jdbcUrl=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.master.username=moksh
spring.datasource.master.password=2005
spring.datasource.master.driver-class-name=org.postgresql.Driver

spring.datasource.slave.jdbcUrl=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.slave.username=moksh
spring.datasource.slave.password=2005
spring.datasource.slave.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect